### ISSUE TITLE
Remove the flashing theme

### ISSUE THREAD

**Issue by cooolgamer** [windows-server-2003/ThirdTube#129]
I don't get why this isn't the case yet, it just hurt your eyes and is useless.

**Comment by Poketubepoggu** [comment]
It is just there for the memes ☢️

**Comment by windows-server-2003** [comment]
☢️

**Comment by goombapatrol** [comment]
Hey, I'd like to request you please reconsider removing the "Flash" option.

I was trying out your program for the first time today and accidentally pressed it when i was scrolling through settings. (I was expecting a "Light / Dark / Follow system time"). After getting full on strobed, I tried to turn it off but it ended up triggering a **bad seizure** and i went unconscious. (I'm photosensitive epileptic). Somebody else had to turn it off for me.

It's a big safety issue, a dangerous "easter egg" in an otherwise quality program. I don't want this to happen to anybody else.

If you absolutely must keep this in your program for some reason, make a popup warning or something so you have to confirm enabling it.

Thanks for making an otherwise nice program. @windows-server-2003
