### ISSUE TITLE
Issue of some channels disappearing

### ISSUE THREAD

**Issue by shadow8493** [windows-server-2003/ThirdTube#142]
Some of the channels that i subscribed just despaired and when i reopened the app the channels aren't there anymore.

**Comment by CyUzi** [comment]
I'm having the same problem. One channel I've identified is rSlash. I've deleted my subscriptions.json to see if the file had an error for permissions or something but that didn't work.

**Comment by windows-server-2003** [comment]
It should be fixed in v0.5.2. I'm sorry if you have lost some of your subscription.
Here's how it happened :
In the subscription save file, there are some information about the subscribed channels like the name, url and the icon url.
When the app reads the subscription file, it checks, for each subscribed channel, whether the icon url is indeed one from YouTube to avoid automatically accessing arbitrary url when the subscription file has been replaced with a malicious one.
However, some channels started to have icon urls that does not match the existing verification pattern and therefore are not loaded. The new version fixed this.

The real problem was that such channels are not only rejected from loading but also removed from the subscription when the subscription was saved. The new version also fixed the behavior and writes back channels that has been marked "invalid". When another unknown legit url pattern appears in the future, some of the subscription might disappear, but after updating the app with a new version that recognizes the new pattern, the lost channels should come back.
