### ISSUE TITLE
Copyrighted videos gives ffmpeg errors..

### ISSUE THREAD

**Issue by jeuularana** [windows-server-2003/ThirdTube#182]
So, since a few months, music videos, or normal videos that have copyright music or sounds, give an error, which says "ffmpeg returned NOT success".
I just want to know if someone can fix the error.

The same problem also happened before, but the creator released an update that corrected it, but now months have passed and it hasn't been updated... :[

**Comment by amberdambey** [comment]
The developer hasn't touched this project for a while. The ffmpeg errors come from the fact that the video is fragmented and cannot be merged since there is no code expecting a video to be fragmented. My workaround is just to turn the video off and use the audio (if it's a music video) so that way I can listen to it at least. Except this doesn't always work unfortunately.

**Comment by windows-server-2003** [comment]
Should be fixed. Sorry for long period of unavailability.
