### ISSUE TITLE
FPS surges on touch

### ISSUE THREAD

**Issue by Budgiee** [windows-server-2003/ThirdTube#24]
FPS surges from 30 to 60 when holding down the stylus on screen.

**Comment by windows-server-2003** [comment]
This is an expected behavior.
The FPS at the top left indicates the rate of rendering.
When the eco mode is on, it only updates the screen when there's a change in the content to display. This means the FPS synchronizes with the FPS of the video. However, it draws the red point that indicates the touch position, so it always updates the screen while touching. Of course, the video continues to play at 30 FPS.

Although this is not a bug, it's confusing for the users, so I'll keep this open and try to find a solution.

**Comment by windows-server-2003** [comment]
I simply removed FPS indicator.
