### ISSUE TITLE
Option to change frame rate between 20 and 60 FPS

### ISSUE THREAD

**Issue by Minionguyjpro** [windows-server-2003/ThirdTube#73]
Add an option to use FPS between 20 and 60 to make it look smoother.

**Comment by windows-server-2003** [comment]
The available video FPS on YouTube are 30 FPS and 60 FPS, and the 60 FPS ones always have resolutions of 720p or higher and are thus not playable.
So the only thing we can do is to play 30 FPS video stream at a lower FPS, but it's difficult to gain performance benefit by that due to the way H.264 compresses video frames.
May have disappointed you, but 30 FPS is the smoothest possible frame rate on 3ds YouTube player.
